name: Release CI

on:
  push:
    tags:
      - "v*"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get go version
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Build binaries
        run: |
          mkdir "-p" dist
          VERSION=${GITHUB_REF#refs/tags/}
          GOOS=linux GOARCH=amd64 go build "-o" dist/mnstrsay-${VERSION}-linux-amd64 ./cmd/mnstrsay

      - name: Generate sha256sum
        run: |
          cd dist
          sha256sum * > sha256sum.txt

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          draft: false
          prerelease: false
